// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBiblioteca.Models;

#nullable disable

namespace WebBiblioteca.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251126225545_ListasClasses")]
    partial class ListasClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBiblioteca.Models.Autores", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Livrosid")
                        .HasColumnType("int");

                    b.Property<int>("editoraID")
                        .HasColumnType("int");

                    b.Property<string>("nacionalidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("id");

                    b.HasIndex("Livrosid");

                    b.HasIndex("editoraID");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("WebBiblioteca.Models.Editora", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Autoresid")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("id");

                    b.HasIndex("Autoresid");

                    b.ToTable("Editora");
                });

            modelBuilder.Entity("WebBiblioteca.Models.Livros", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int>("Paginas")
                        .HasColumnType("int");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("publicacao")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("qtd")
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("volume")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("AutorId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("WebBiblioteca.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("acesso")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebBiblioteca.Models.Autores", b =>
                {
                    b.HasOne("WebBiblioteca.Models.Livros", null)
                        .WithMany("listaAutores")
                        .HasForeignKey("Livrosid");

                    b.HasOne("WebBiblioteca.Models.Editora", "Editora")
                        .WithMany()
                        .HasForeignKey("editoraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editora");
                });

            modelBuilder.Entity("WebBiblioteca.Models.Editora", b =>
                {
                    b.HasOne("WebBiblioteca.Models.Autores", null)
                        .WithMany("listaEditora")
                        .HasForeignKey("Autoresid");
                });

            modelBuilder.Entity("WebBiblioteca.Models.Livros", b =>
                {
                    b.HasOne("WebBiblioteca.Models.Autores", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("WebBiblioteca.Models.Autores", b =>
                {
                    b.Navigation("listaEditora");
                });

            modelBuilder.Entity("WebBiblioteca.Models.Livros", b =>
                {
                    b.Navigation("listaAutores");
                });
#pragma warning restore 612, 618
        }
    }
}
